version: "3.8"

services:

  # mongodb:
  #   image: mongo:latest
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: mongoadmin
  #     MONGO_INITDB_DATABASE: django_mongodb_docker
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - /mongodb/mongod.conf:/etc/mongod.conf
  #     - /mongodb/data:/data/db

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - .env
    # networks:
      # - db_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    container_name: back
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
        --no-input && gunicorn -b 0.0.0.0:8000 config.wsgi --reload"      
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/opt/services/ceres
      - ./static/static_data:/opt/services/ceres/back_static
      - ./static/media_data:/opt/services/ceres/back_media
    depends_on:
      - db
    links:
      - db

volumes:
  postgres_data: